### ISSUE TITLE
RemoteDesktop Text1 Text2 Text3 Text4 additionally path Managed Preferences

### ISSUE THREAD

**Issue by micneu72** [munkireport/ard#2]
We use the Apple Profilmanager, where we set the text4 from the RemoteDesktop for each client. If you do it manually, the value is written to the "`/Library/Preferences/com.apple.RemoteDesktop`". The profilmanager writes the value here "`/Library/Managed\ Preferences/com.apple.RemoteDesktop`".

**Comment by bochoven** [comment]
Fixed with the latest release I hope!
